version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "selenium-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1elewl2orb0ub"
s3_prefix = "selenium-serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
